spring.application.name=learn-spring-ai

# Ollama configuration

spring.ai.ollama.base-url= http://localhost:11434

# Chat Model Configuration
spring.ai.ollama.chat.options.model= tinyllama:latest
spring.ai.ollama.chat.options.temperature=0.7

# Embedding Model Configuration
spring.ai.ollama.embedding.model= nomic-embed-text:latest

# OpenAI configuration

spring.ai.openai.api-key= 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
spring.ai.openai.chat.options.model= gpt-3.5-turbo
spring.ai.openai.chat.options.temperature=0.7

# Vector Store Configuration

spring.ai.vectorstore.pgvector.initialize-schema= true

spring.datasource.url= jdbc:postgresql://localhost:5433/pgvector-testing
spring.datasource.username= postgres
spring.datasource.password= postgres
spring.datasource.driver-class-name= org.postgresql.Driver

# Chat Memory Configuration Advisor

spring.ai.chat.memory.repository.jdbc.intilialize-schema= always
spring.ai.chat.memory.repository.jdbc.table-name= chat_memory